### ISSUE TITLE
Smart charging

### ISSUE THREAD

**Issue by Martin-BW** [fondberg/easee_hass#102]
I try to change the smart charging state. I only can switch it on by using the easee.smart_charging service.

If I switch it by using switch.easee_home_12345_smart_charging, it tells me that only one parameter is defined, but 2 are given and it's not changing the smart charging state.

How could I change this state ?

Martin

**Comment by tmjo** [comment]
Hmm, rings a bell, I think this is an old sin. I can take a look at it, if I remember correctly this function is a toggle function in Easee API while we had it is a on/off.

**Comment by tmjo** [comment]
Did a quick check, and you're perfectly right. The service itself is working, but the switch implementation is not since it is sending a true/false or on/off value which is not accepted in the other end. We'll find a fix for this, should be easy. Thanks for reporting.

**Comment by Martin-BW** [comment]
Hi, 

 

That’s great.

 

I can set it by using https://api.easee.cloud/api/chargers/EH12345/settings , parameter "smartCharging":  true or false.

 

I first thought the service would be a toggle, bur it only switches smart charging on, not off.

 

Martin

**Comment by tmjo** [comment]
Please follow [PR on pyeasee](https://github.com/fondberg/pyeasee/pull/40). I've tested and works fine for me.

**Comment by Martin-BW** [comment]
How can I use the fix in easee_hass in Home Assistant ?

**Comment by astrandb** [comment]
We will test the fix internally and include it in next release of the integration. It is a bit complicated to patch manually if you are not deep into development of this type of applications.

**Comment by Martin-BW** [comment]
Okay. Thank you very much for your efforts.

Greetings from Germany.

Martin

**Comment by Martin-BW** [comment]
When do you plan to release the next version of the integration?

**Comment by astrandb** [comment]
The library will be released today or tomorrow. After that we can release the integration.

**Comment by Martin-BW** [comment]
Works great. Thank you all.
