### ISSUE TITLE
Services and their usage

### ISSUE THREAD

**Issue by stigvi** [fondberg/easee_hass#105]
easee.set_charger_dynamic_current
easee.set_charger_circuit_dynamic_current
easee.set_circuit_dynamic_current

Can someone explain to me the differences between these 3 service calls?

**Comment by olalid** [comment]
easee.set_charger_dynamic_current: A current limit applied locally at the charger.

easee.set_charger_circuit_dynamic_current and easee.set_circuit_dynamic_current: both result in the same thing, the difference is that the handle used is either charger or circuit id. This is a current limit that applies to a circuit. If more than one charger is connected to a circuit they will share this current.

The resulting current limit is the lowest one of all the set current limits.

**Comment by olalid** [comment]
@stigvi if this answers your question, please close the issue.

**Comment by stonemaan** [comment]
I am facing the problem, that the easee.set_charger_dynamic_current is being ignored after a few seconds and the output limit slowly increases until max output limit is reached. example: I set the easee.set_charger_dynamic_current to 6 amps, my charger starts charging, and slowly the output limit increases to 12... has anybody a solution for that?

**Comment by olalid** [comment]
Use the circuit dynamic current instead.

**Comment by BlueAndi** [comment]
Because I want to create some scripts for solar driven charging, I read a little bit about the cloud API and created a first overview:
![grafik](https://user-images.githubusercontent.com/9699465/113361255-d298ed80-934b-11eb-8a1f-cb5c5ddd1c06.png)
