### ISSUE TITLE
No module named 'signalrcore.transport'

### ISSUE THREAD

**Issue by ankisch** [fondberg/easee_hass#106]
Thanks for a great component.

After upgrading to HA Core 2021.03.2 this morning Easee would not load with the following error.

`Unable to import component: No module named 'signalrcore.transport'`

I removed the component, which I installed before you made it to HACS default, and reinstalled from the default repository. Now when I try to add the integration in HA I get the following error

`Error occurred loading configuration flow for integration easee: No module named 'signalrcore.transport'`

**Comment by astrandb** [comment]
Thank you for reporting.
This is due to breaking changes in the signalrcore library. We are investigating...
