### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by freber** [fondberg/easee_hass#107]
After installing the custom component through HACS I can't configure it. I get this error from Configurations->Integrations.

I'm running core-2021.3.2 and supervisor-2021.03.4

<img width="720" alt="Screenshot 2021-03-07 at 14 06 42" src="https://user-images.githubusercontent.com/1684291/110240922-68f51180-7f4e-11eb-8db2-de771b721991.png">

Best regards,

**Comment by astrandb** [comment]
This is due to a breaking change in an upstream library. We are investigating...

**Comment by freber** [comment]
Ah, got it. Any way to condigure the integration manually?

Best regards

**Comment by olalid** [comment]
websocket-client lib needs to be version 0.57.0 and signalrcore lib needs to be 0.8.8. Later versions are not compatible (at least not right now).
We are working on a fix.
