### ISSUE TITLE
New error message?

### ISSUE THREAD

**Issue by casperse** [fondberg/easee_hass#108]
Hi Love this plugin!

this has been working 100% since installation for +5 months but after the last Easee update I get this error
![image](https://user-images.githubusercontent.com/2026859/110320402-85598280-8010-11eb-8195-e3a7f0694262.png)
And all the sensors are now off-line

The Easee APP on my phone works 100% so something in the integration might have changed?
Running latest HAC version of the easee_hass and latest Hassio version

**Comment by astrandb** [comment]
This is due to a breaking change in signalrcore library. We have fixed the problem and are planning to release a new version later today.
