### ISSUE TITLE
Cannot call service on turn_on/off smart_charging()

### ISSUE THREAD

**Issue by oakhill87** [fondberg/easee_hass#111]
I am unable to use the Switch entity to turn on or off the Smart Charging.
When using the Easee-app, I see the change instantly in HA, but using the switch returns the following:

"Failed to call service switch/turn_on/off. smart_charging() takes 1 positional argument but 2 were given"

**Comment by tmjo** [comment]
Hi, which version of the integration are you using? This should have been fixed in one of the latest releases, and I don't get this error message in my installation anymore. Please check if you have the latest version (0.9.8).

**Comment by oakhill87** [comment]
Reinstalled the plugin, and it worked. Seems I was not getting any HACS updates.

But the current version I see is 0.9.29, not 0.9.8.

**Comment by tmjo** [comment]
Yes, 0.9.29 was released yesterday (and I've got a typo in my message, should say 0.9.28 at the time of writing). Please close issue if it seems to be working well in your end now.

**Comment by oakhill87** [comment]
You got it.
cheers.
