### ISSUE TITLE
binary_sensor.easee_home_#####_online not disconnected?

### ISSUE THREAD

**Issue by 1v4r** [fondberg/easee_hass#116]
Hi. Is this sensor reporting the connection between the integration to Easee's servers or the connection between Easee's servers and the charger? My Easee mobile app reports the chager as being offline (as I have pulled the circut braker) but the binary sensor reports claims it's online. The other sensors work as expected. It would be cool if this could report on the charger being offline as I would like to use this as a way to notify me if the charger trips the circut braker or goes offline and stops charging the car.

**Comment by olalid** [comment]
The intention is that sensor should change to offline state when the charger (I assume you are talking about a charger) has not sent any updates for 17 minutes independent of the reason. You should be able to see the time when the last update known as "latestPulse" was received if you look at the attributes of the sensor. It is updated every time some new data is received from the cloud servers.
What you are saying seems strange, a charger that has no power should not be able to send updates. But maybe it is just a question of waiting 17 minutes?

**Comment by olalid** [comment]
Please close the issue if this solved your problem.

**Comment by olalid** [comment]
Closing due to lack of further activity.
