### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by vibrog** [fondberg/easee_hass#117]
How often do the integration call the Easee API?
Easee blocked my IP-address because it was making too many requests...

**Comment by olalid** [comment]
It does normally not poll the API at all more than at once startup, after that data is streamed from the easee server so there is no reason to call the APIs unless some service in HA is called that results in an API call.
Are you sure you are blocked?
Some of the Easee APIs will return errors if they are called too often, it is so to speak "normal" behaviour.

Would be interesting to hear more about your specific case... Can you provide some logs or tell us more details?

**Comment by olalid** [comment]
I should add that it will fall back to polling if the streaming connection is lost for some reason.
If that is the case it should reconnect after a while, but if there is some problem on the server side the polling may continue until that is resolved.

**Comment by vibrog** [comment]
That's what I thought.
My integrations only interact with it when leaving/arriving home.
I got this e-mail from Easee:

> **Subject: P blocked because of excessive use**
> We have noticed excessive use of our cloud services on your Easee account. Because of the nature of the use we have had to block your IP address in our cloud service.
>
> Why does this happen?
> Your Easee account is most likely used in an external integration like home automation or other use of the Easee public API.
>
> How can I fix this?
> You can disable any possible integration you have using your Easee account or disable the function you believe may lead to the excessive use. Please let us know when it is disabled so we can unblock your IP address again.

**Comment by olalid** [comment]
What version are you using? There is a bug fix in the latest release for a reconnect issue, where it would cause excessive traffic if the server was restarted.

**Comment by olalid** [comment]
Ok, I had a chat with Easee, they have removed all blocked IPs, so you should be fine again.
But please make sure you are running the latest release, 0.9.30, there is a bug in previous versions that under certain circumstances will cause excessive reconnect attempts. If you were running an older version I think that is a likely reason for your problem.

**Comment by olalid** [comment]
Please close the issue if this solved your problem.

**Comment by olalid** [comment]
Closing due to lack of further activity.
