### ISSUE TITLE
Incorrect sensor state class

### ISSUE THREAD

**Issue by kristianolofsson** [fondberg/easee_hass#141]
The sensor state class "measurement" is getting depreciated and replaced with "total_increasing"

https://developers.home-assistant.io/blog/2021/08/16/state_class_total/?fbclid=IwAR2jZqRsgMIYHAwdXCnQFoktmWK__K2gub0OFhc1LiIMtndYQjO6m2QCpow

**Comment by astrandb** [comment]
We are aware, and it will be fixed in an upcoming release.
Duplicate of #138
