### ISSUE TITLE
Be able to set charger (or site?) current/power limit for PV charging

### ISSUE THREAD

**Issue by jonasdiemer** [fondberg/easee_hass#143]
It would be great if the integration allowed setting the max current/power to be used for charging. This would enable charging with excess power from photovoltaics.

I think this is a site-setting (as opposed to charger setting) in the Easee app / API.

Thanks!

**Comment by olalid** [comment]
There are already services in the integration which allows you to set all of the current limits that are supported by the easee API. Generally I recommend that you use the dynamic circuit limit. It is as close to a site-wide setting that you can get.
It also allows you to control which phase to use in a 3-phase system.
Search the otters reported issues, this has been discussed several times before.

**Comment by jonasdiemer** [comment]
Thanks a lot! I've found e.g. https://github.com/fondberg/easee_hass/issues/120 (in case someone else stumbles on this issue).

I got confused by the README.md mentioning only sensors. Maybe it would help to update it (I can give it a shot, if you'd accept PR on it).

While at it: README.md mentions integration into mainline HA, but the corresponding PR is closed - what's the status there (and should it be reflected in README.md)?

**Comment by olalid** [comment]
The documentation is lacking for sure, help will be appreciated. You may want to look at the stuff we wrote for the core integration: https://github.com/fondberg/home-assistant.io/blob/easee/source/_integrations/easee.markdown even though it is also outdated by now.

There are some hurdles to pass to get it in to the core HA project and for now we feel it is better to focus on getting a well working custom component.

**Comment by jonasdiemer** [comment]
Thanks, I think this can be closed.
