### ISSUE TITLE
Cannot authenticate + outdated readme

### ISSUE THREAD

**Issue by ronnydahl** [fondberg/easee_hass#152]
Hey,

First up, I like the initiative and look forward to it being stable. 

After installing the component through HACS, rebooting and attempting to set up the authentication, I get an "Unable to connect to Easee. Check your username and password." message after using config flow. I'm positive that the credentials are correct as I'm both using the Easee Android app as well as that I've logged on to https://developer.easee.cloud/ . I can also list the Easee charger from one of the endpoints there.

Secondly (or thirdly, depends on how you count), the readme for the project is updated. The PR notice on the bottom is stale AF. Should probably be updated ;)

Love,
R

**Comment by olalid** [comment]
Hi,

That sounds very strange, I assure you that the login works, so there must be something wrong with your credentials somehow.
Does the username look correct in the log files?
You need to enable debug logs for pyeasee.easee and custom_components.easee to see the relevant information.

**Comment by ronnydahl** [comment]
Thanks for your feedback, @olalid ! After enabling custom logging (which I should've done prior to writing the original message), I discovered that the mail address wasn't successfully verified (although I had verified it earlier). After manual verification, the login flow works as expected. Thanks!
