### ISSUE TITLE
Integration with equalizer

### ISSUE THREAD

**Issue by riksarchen** [fondberg/easee_hass#159]
Hey,
Thanks for your hard work with this integration. 

An idea or question regarding Easee Equalizer. Any chance it could be implemented so your could get data from the equalizer into home assistant like you can with Tibbers Pulse P1?

Thanks!

**Comment by olalid** [comment]
Hi,
Thanks.

Yes, equalizer is already supported.

**Comment by prilly-dev** [comment]
Equilizer works like a dream,
