### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by andzie82** [fondberg/easee_hass#168]
I get this error when selecting my site in the gui. 

User input malformed: Fastcharger is not a valid option for dictionary value @ data['monitored_sites']

**Comment by astrandb** [comment]
We need som more info to troubleshoot this:
- Are you running latest version of the integration?
- Can you describe in more detail in what situation this happens. First Install or when updating an existing configuration?
- If the integration is loaded, please upload a diagnostic download.
- Please send a screenshot of the screen just before this error is displayed.

**Comment by astrandb** [comment]
@w0vka Thank you for pinpointing where the problem is. We will fix it...
