### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by bjestavs** [fondberg/easee_hass#170]
I have downloaded the package through HACS but I can't get HA to install it. Keep getting the error "Config flow could not be loaded" even though I have removed it and tried again and tried with a previous version with another config flow and disabling google cast. What could be wrong?

**Comment by astrandb** [comment]
We have not seen this problem before.
Need some more info in order to troubleshoot.
What version of Home Assistant are you on? If not the latest, please upgrade to HA 2022.2.
Have you restarted HA?

**Comment by bjestavs** [comment]
I updated HA and it worked. Thank you!

**Comment by astrandb** [comment]
To prevent that this happens for other users we should update HA version requirement in hacs.json to at least 2022.1.
Fix in next release.

**Comment by astrandb** [comment]
@simonengelhardt  We have not been able to reproduce this error with recent versions of HA. There are many hundreds of installations without this problem so we need to understand how the error is triggered in your setup.
Could you please enable full debug log by entering following in your configuration.yaml, restart HA and clear the browser cache:
```yaml
logger:
  default: debug
  logs:
    custom_components.easee: debug
    pyeasee: debug
```
Then try to install the Easee integration again.
Please also describe the sequence of actions leading up the error.

**Comment by simonengelhardt** [comment]
@astrandb Thanks for looking into it. I tried again after adding the debug config and restarting – and of course the installation just works now 🙄
I removed the debug config again, restarted, and it still works! So.. I guess this was just some fluke and maybe I'll never know what happened.
Anyway, thanks again for your help. Looking forward to playing around with the component.
