### ISSUE TITLE
Multiple Easee Home - Start/Resume

### ISSUE THREAD

**Issue by mgk73ea** [fondberg/easee_hass#189]
### Question

Hi, 
First - Lots of kudos to you from me.
I have two linked Easee Home PV-chargers. Need to start and pause each charger individually (Play/Pause is possible in the Easee-app). Is it possible in HA? 

Best regards
Magnus

### What version of the integration are you using?

latest

**Comment by astrandb** [comment]
Pause and resume are available as services. Have a look in Developers tools -> Services.

**Comment by mgk73ea** [comment]
Thanks Åke! Where do I find "Developers tools". //Magnus (noob)

**Comment by astrandb** [comment]
See below:
Note that there are no built-in buttons for Pause/Resume in the Easee integration. But you can create similar functionality with Input entities and automations. But that can be a challenge if you classify yourself as a noob :wink:
![image](https://user-images.githubusercontent.com/5016010/169685104-bd7ed852-2e1d-4ef9-ba43-4170b16b3ca9.png)

**Comment by mgk73ea** [comment]
Thanks! 

Tried following with this result. - "Could not find charger"

```
service: easee.resume
data:
  "charger_id": "INSIDAN-EH123456"
```

**Comment by astrandb** [comment]
Try to remove "INSIDAN-"
Your charger_id is displayed as an attribute on the status sensor.

**Comment by mgk73ea** [comment]
Same result. I renamed my chargers in the Easee-app. The easee_hass integration finds my two chargers by custom name. Everything else works with my custom names.

**Comment by mgk73ea** [comment]
Ok I find the real name of the charger in the Easse-app. Now It works. Thanks alot!

**Comment by astrandb** [comment]
Excellent!
There are differnt flavours of names in Home Assistant. `Entitiy names` and `Friendly names`. The service call need the `Charger ID` which is hard-coded into the device. If you click on the charger status sensor and open Attributes you will find a lot of internal data.
