### ISSUE TITLE
Bad request service 400

### ISSUE THREAD

**Issue by osulivanDE** [fondberg/easee_hass#191]
### The problem

Hey, since a few hours i can´t get values in HA from my easee devices. I already deleted the integration and reincluded it but the error persists. 
Basic communication to the webservice seems to work because i can see my different sites and devices while integrating but none of the values from my Easee Devices are getting updated.

In my Protocol log i can see the following Errors:

////////////////////
Logger: pyeasee.easee
Source: /usr/local/lib/python3.9/site-packages/pyeasee/easee.py:48
First occurred: 13:08:57 (76 occurrences)
Last logged: 16:43:52

Bad request service (400: {'errorCode': 410, 'errorCodeName': 'ChargerDisconnected', 'type': None, 'title': 'Charger disconnected', 'status': 400, 'detail': '[Empty in production]', 'instance': None, 'extensions': {}} https://api.easee.cloud/api/chargers/MYID/commands/resume_charging)

////////////////////
Logger: pyeasee.easee
Source: /usr/local/lib/python3.9/site-packages/pyeasee/easee.py:63
First occurred: 13:03:26 (11 occurrences)
Last logged: 14:09:02

Server failure(503: https://api.easee.cloud/api/sites/331538/state)
Server failure(503: https://api.easee.cloud/api/sites)
Server failure(503: https://api.easee.cloud/api/chargers/MYID/commands/resume_charging)
Server failure(502: https://api.easee.cloud/api/chargers/MYID/commands/resume_charging)
Server failure(504: https://api.easee.cloud/api/chargers/MYID/commands/resume_charging)

### Version of Easee integration having the issue?

v0.9.43

### Version of Home Assistant Core having the issue?

core-2022.6.5

### Anything in the logs that might be useful for us?

```txt
Maybe this has tomething to do with the recent HA update core-2022.6.5?
```

**Comment by olalid** [comment]
I think this is a problem on the server side, I had similar problems earlier today, but it is working again now.

**Comment by osulivanDE** [comment]
Thank you. This gives me hope it is going to fix itself. I think that when the local API for the wallboxes comes at some point, things like this will no longer be a problem.

**Comment by osulivanDE** [comment]
The Problem ist solved now. Everything works again. Seemed to be the API which was down for a few hours.
