### ISSUE TITLE
Charger information "unavailable"

### ISSUE THREAD

**Issue by ujhede** [fondberg/easee_hass#198]
### The problem

Since installing the HA 2207.7.*  none of my two easee chargers show any status in Home Assistant and all entities are marked as unavailable.

I have tried restarting HA, disabling and re-enabling the integration and even deleted and re-added it.

  

### Version of Easee integration having the issue?

Latest

### Version of Home Assistant Core having the issue?

2022.7.0-3

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/easee/controller.py:416
Integration: Easee EV charger (documentation, issues)
First occurred: 20:29:48 (6 occurrences)
Last logged: 20:34:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 416, in refresh_sites_state
    charger_data.state = site_state.get_charger_state(charger_id, raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/site.py", line 128, in get_charger_state
    return ChargerState(charger_data["chargerState"], raw)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 56, in __init__
    data = {
TypeError: 'NoneType' object is not a mapping
```

**Comment by olalid** [comment]
I think this is the same issue that this PR is trying to solve: https://github.com/fondberg/easee_hass/pull/194
I.e. it is the Easee API that sometimes seems to allow you to log in, but then it the other API function just do not return anything.
So you are probably just unlucky that the easee servers again have this issue right after you have updated to 2022.7.x

**Comment by olalid** [comment]
Can you please report if you still have the issue or not?

**Comment by ujhede** [comment]
Sorry for asking stupid questions but how do I upgrade to the "patched" version when  the PR has not been merged yet?

**Comment by ujhede** [comment]
Update I  just installed the new HA release 2022.7.4 and now my easee integration is working again.  I even restarted HA a couple of times and it is still working.

**Comment by olalid** [comment]
> Sorry for asking stupid questions but how do I upgrade to the "patched" version when the PR has not been merged yet?
> 
> Forgot to mention that I am using the git installation method.

I did not mean that you should use the PR, my question was more: did the problem resolve itself when the Easee API servers again started to answer the API request correctly?

**Comment by olalid** [comment]
To be closed when PR https://github.com/fondberg/easee_hass/pull/194 is merged.
