### ISSUE TITLE
Startup error 'NoneType' object is not a mapping

### ISSUE THREAD

**Issue by Hagsten** [fondberg/easee_hass#208]
### The problem

After upgrading from OS 7.6 to 8.6 (I think) the following error appeared on startup making the integration load but all sensors unavailable. I have re-installed the integration with the same issue. I have restarted HA and RPI. Still same issue.

Logger: homeassistant
Source: custom_components/easee/controller.py:421
Integration: Easee EV Charger ([documentation](https://github.com/fondberg/easee_hass), [issues](https://github.com/fondberg/easee_hass/issues))
First occurred: 2:39:18 PM (90 occurrences)
Last logged: 4:07:15 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 421, in refresh_sites_state
    charger_data.state = site_state.get_charger_state(charger_id, raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/site.py", line 128, in get_charger_state
    return ChargerState(charger_data["chargerState"], raw)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 56, in __init__
    data = {
TypeError: 'NoneType' object is not a mapping

### Version of Easee integration having the issue?

easee-0.9.44

### Version of Home Assistant Core having the issue?

core-2022.8.6

### Anything in the logs that might be useful for us?

```txt
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 421, in refresh_sites_state
    charger_data.state = site_state.get_charger_state(charger_id, raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/site.py", line 128, in get_charger_state
    return ChargerState(charger_data["chargerState"], raw)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 56, in __init__
    data = {
TypeError: 'NoneType' object is not a mapping
```

### Additional information

![image](https://user-images.githubusercontent.com/6681912/188657779-90c3bd08-bba2-4fbe-93d6-c079566cbcff.png)

More info about system

  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.08.5",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },

**Comment by larserhardsen** [comment]
Yes, it seems that the chargerConfig and chargerState parts of the api response are now empty:

![image](https://user-images.githubusercontent.com/3054735/188661144-f22880e8-8561-40dd-81ea-38af7d2ec37f.png)

**Comment by olalid** [comment]
Yes, it is a change on the server side that causes this, we are investigating.

**Comment by olalid** [comment]
Solved in https://github.com/fondberg/easee_hass/pull/210
