### ISSUE TITLE
Easee sensors not being populated

### ISSUE THREAD

**Issue by kolaf** [fondberg/easee_hass#211]
### Question

I installed the easee integration from HACS and set it up in the integrations page by logging in with my easee cloud credentials. This seemed to work without a hitch. However, no data is populated for any of the sensors provided by the integration as seen in the below screenshot.
![image](https://user-images.githubusercontent.com/1871212/188812840-c399577c-fe02-437a-8236-fd43e4a0b53c.png)
Charging has been running for more than an hour, and the web and app interfaces from easee provide relevant information for the ongoing charging session.
![image](https://user-images.githubusercontent.com/1871212/188813486-77740011-2d10-40d5-b72c-efde71ccab02.png)
I have tried restarting the integration. I see the following in the log file, but I suspect this is simply because it is not finding any data:
`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/easee/controller.py:421
Integration: Easee EV Charger (documentation, issues)
First occurred: 8:18:19 AM (56 occurrences)
Last logged: 9:12:20 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 421, in refresh_sites_state
    charger_data.state = site_state.get_charger_state(charger_id, raw=True)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/site.py", line 128, in get_charger_state
    return ChargerState(charger_data["chargerState"], raw)
  File "/usr/local/lib/python3.10/site-packages/pyeasee/charger.py", line 56, in __init__
    data = {
TypeError: 'NoneType' object is not a mapping
`

### What version of the integration are you using?

easee-0.9.44

**Comment by astrandb** [comment]
This is most likely the same issue as #208 
Please upgrade to v0.9.45

**Comment by kolaf** [comment]
Prompt and on point, couldn't ask for more :D. Thank you very much.
