### ISSUE TITLE
Status is incorrect

### ISSUE THREAD

**Issue by jockesoft** [fondberg/easee_hass#212]
### The problem

Seems like something is broken with the status when the car is charging, my status is "Waiting" even if it is charging as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/78916821/188859987-2cce6ef1-d6cf-4ecc-a4c8-6b294f050aa0.png)

### Version of Easee integration having the issue?

0.9.45

### Version of Home Assistant Core having the issue?

2022.8.7

### Anything in the logs that might be useful for us?

```txt
No error messages seen in the logs
```

**Comment by Wiigian** [comment]
Is this still an issue? Easee has been having some trouble today, check their status page:

[https://status.easee.com/](url)

**Comment by jockesoft** [comment]
Yes, this is a problem now and I have restarted several times and according to easee the issue they were having should have been resolved.

**Comment by olalid** [comment]
I have not seen this issue on my installation but I will watch for next time I charge.

**Comment by olalid** [comment]
Well, for me this works as expected.
Do you still have the problem @jockesoft ?
There has been quite substantial performance problems with the Easee cloud the last 24 hours, so it could be related to that perhaps.

**Comment by jockesoft** [comment]
Agree, seems to be working here as well, temporarily glitch I guess.
