### ISSUE TITLE
Do not start charging on plug-in

### ISSUE THREAD

**Issue by kolaf** [fondberg/easee_hass#213]
### Question

This is probably something that has been discussed before, but I haven't found anything in the open support issues.

I have created two automations, one for starting charging when nordpool has a low price, and one to stop charging when the prize is not low.  Initially I used the pause and resume services to do this, but after reading a bit further I have changed this to set_charger_dynamic_limit. I set this to the maximum rate of the system (32A) when I wish the charting to start, and to 0 when I wish it to stop. This works quite well as long as the car is plugged in.  

The problem is that when I have been out driving and plug the car in, the charger immediately starts. I have to pause it manually through the app, and then it will be restarted later from the automation. How do I avoid it starting automatically when it is plugged in? I have tried both with and without smart charging (Tibber, I am not a customer so they only provide the overload protection), but that does not seem to make any difference. I'm not sure if smart charging is a prerequisite for overload protection?

To help me out with planning the charging I get a notification when I plugged the car in with an estimate of the remaining charge time. This allows me to optionally start charging immediately if I see that the estimate is close to when I need the car next (it's a 2014 leaf, so frequent charging is required :P)

### What version of the integration are you using?

0.9.45

**Comment by tmjo** [comment]
As far as I recall, Easee is resetting the dynamic limit when reconnected which corresponds to what you experience. I guess an automation setting your desired limit upon connection could do the trick. An alternative approach can be trying the 'dynamic circuit limit' instead. Not 100% sure, but I don't think this is changed by Easee. If you have one charger, the two limits basically do the same, but if you have more than one on the same circuit, they obviously behave differently.

Personally, I've setup scheduled charging where I don't allow the charger to start until late night, and then during this period I use the dynamic charger limit to avoid high peaks in power. For me this works well, and it effectively avoids that the charger starts when I plug it in. The drawback is that if it is cheap during daytime I won't benefit from this. There is a 'override schedule' service that you can call which does exactly that, and an automation could for instance be made to override a schedule in case price is low or something like that.

**Comment by olalid** [comment]
Use circuit dynamic limit instead, it should solve your problem.

**Comment by kolaf** [comment]
Perfect, thanks. That did the trick.
