### ISSUE TITLE
Missing voltage

### ISSUE THREAD

**Issue by prilly-dev** [fondberg/easee_hass#214]
### The problem

seems there are missing voltage attributes

![bilde](https://user-images.githubusercontent.com/66376450/190844303-2ef341bc-e037-4115-88ad-7e981906f268.png)

### Version of Easee integration having the issue?

Latest

### Version of Home Assistant Core having the issue?

latest

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information

seems the api has stopped providing this extra voltages

**Comment by olalid** [comment]
This is normal behavior. Only the measurements that makes sense are available depending on what type of electrical system you have where you live.
I.e IT, TN, etc.

**Comment by prilly-dev** [comment]
No its not.I have used this voltages for 2 years now and they disappeard a couple of weeks ago.Something has changed.
-------- Opprinnelig melding --------Fra: Ola Lidholm ***@***.***> Dato: 17.09.2022  14:33  (GMT+01:00) Til: fondberg/easee_hass ***@***.***> Ko: prilly-dev ***@***.***>, Author ***@***.***> Emne: Re: [fondberg/easee_hass] Missing voltage (Issue #214) 
This is normal behavior. Only the measurements that makes sense are available depending on what type of electrical system you have where you live.
I.e IT, TN, etc.

**Comment by prilly-dev** [comment]
No its not normal behavior, i have used all of this voltage atributes for 2 years, they stoped providing values 14 september at 20.38 gmt+2 when i check the history of this entities.

there has been no changes to my charger in this time, and i am supposed to have this voltages.

Either there is something wrong in the integration or easee has stopped providing this voltages.

**Comment by olalid** [comment]
What electrical system do you have and which ones have you been using before?

**Comment by prilly-dev** [comment]
i have TN and i use three phases. i have used all voltage parameters before.

i did check the api, seems the values are missing from Easee API, i have made a ticket with them to investigate

![bilde](https://user-images.githubusercontent.com/66376450/190858665-88eadd55-a744-4866-8360-6f911285b5fa.png)

**Comment by olalid** [comment]
If you have TN these are the 3 voltages you should be using that is still available.

**Comment by prilly-dev** [comment]
> If you have TN these are the 3 voltages you should be using that is still available.

I dont think you know much about this. The missing voltages can be used for alarms if there are fault scenarios. If the t1t2 voltages increases above 1 to 2 volt it might be a ground or neutral fault.

So in my case as a electrical engineer I tell you this 3 voltages you are refering to are not sufficient in all cases.

But iam not here to discus what I use them for or to educate you in electrical engineering, I just tell you there is something wrong and that error has now been located to easee cloud api and not the integration so I will close this ticket now.

**Comment by olalid** [comment]
Thank you for calling me stupid.
(M Sc E.E. myself if that is important).
If you do not like the way this HA component works, feel free to stop using it.

**Comment by prilly-dev** [comment]
> Thank you for calling me stupid. (M Sc E.E. myself if that is important). If you do not like the way this HA component works, feel free to stop using it.

I did not say that and I appreciate your work on this integration, I find it very well made and thank you for it.

This issue here is i tell you the reported voltages is missing sins the 14.sep. iam not interested in explaining what I use them for or to be told what to use. I strictly wanted to know where the error is and that has been located. 

Iam sick of beeing attacked when I report a issue.

**Comment by tmjo** [comment]
Instead of feeling sick for being attacked when reporting an issue, you should consider changing your tone when reporting. These integrations are made for free by by somebody not earning a dime on spending their spare time on doing it. Perhaps there is a problem with the API itself and not the implementation, or perhaps it is a bug. Both are possible, but your tone doesn't encourage fixing it.

**Comment by prilly-dev** [comment]
Easee aktiverte diagnostic mode på min lader, det ordnet saken.
