### ISSUE TITLE
Enable TimeToLive parameter (for dynamic charging currents) in service call

### ISSUE THREAD

**Issue by thejellybear** [fondberg/easee_hass#218]
### Feature request

Easee API as well as the [pyeasee function set_dynamic_charger_circuit_current](https://fondberg.github.io/pyeasee/pyeasee/charger.html#pyeasee.charger.Charger.set_dynamic_charger_circuit_current) appear to support a TimeToLive parameter. It allows the charger to revert to the offline current setting if it hasn't received an updated dynamic_charger_circuit_current service call within the specified time, e.g. if cloud connection is lost.

That parameter is however not accessible through the Homeassistant integration service call today. Would it be possible to enable it?

![Capture](https://user-images.githubusercontent.com/107751148/193759335-6e7db344-8d7b-46b2-8581-6811fe535441.jpg)
![Untitled](https://user-images.githubusercontent.com/107751148/193759348-0bec7062-9fa8-491e-90bc-3cdef90b069e.png)

### What version of the integration are you using?

easee-0.9.43

**Comment by olalid** [comment]
Yes, this is on our to-do list.

**Comment by olalid** [comment]
See also https://github.com/fondberg/easee_hass/issues/199

**Comment by thejellybear** [comment]
Ah, excellent. Looking forward to the fix! :)

**Comment by olalid** [comment]
See https://github.com/fondberg/easee_hass/pull/222
