### ISSUE TITLE
Can't find the integration anywhere

### ISSUE THREAD

**Issue by robinpersson** [fondberg/easee_hass#226]
### The problem

Installed according to readme. Clear cache. Still I can't find the integration anywhere...

### Version of Easee integration having the issue?

v0.9.45

### Version of Home Assistant Core having the issue?

2022.10.3

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by astrandb** [comment]
Well, you have probably missed something...
- Install the integration via HACS
- Restart Home Assistant
- Add integration from Settings->Integrations -> Add integration (Clear browser cache - if needed)

**Comment by robinpersson** [comment]
Found it from the phone app
