### ISSUE TITLE
cablelocked and consumption_days_1 does not seam to update

### ISSUE THREAD

**Issue by nsimb** [fondberg/easee_hass#23]
Release 0.9.12 and previous

cablelocked does not update any mater if I lock or unlock it
consumption_days_1 remains 0, the other time intervals are working fine. Also, the session_energy is working fine and increases during the day.

Let me know if I can help in any way or supply more information if you can replicate the problem

Thanks for all the changes, really happy with this integration

**Comment by tmjo** [comment]
Correctly observed, I saw the same and have fix ready. Problem seems to me that cableLock is not set by Easee API when it is permanently locked, not sure if it is intentional or a bug. Anways, I've got a plan to fix it quite soon :)

I'll check the consumption_days_1, perhaps it is too small interval for the API. As you say, the session_energy shows current session and should probably give a "similar" value to what was expected. Perhaps it is about the timestamp, but I'll check.

**Comment by fondberg** [comment]
My consumption 1 day works. Can it be tjat there os a slight delay in easee's database?

**Comment by olalid** [comment]
Still waiting for my car, so can not be of much help in testing functions where a car is needed I am afraid.

**Comment by fondberg** [comment]
I can test it today

**Comment by tmjo** [comment]
I'll try to test it in my end as well. If my HA Recorder is to trust, I couldn't see movement in the sensor during my last charging while the session_energy stepped up nicely. Can it be that this call only updates after completed charger or at end of day or something?

Proposal to fix cableLocked is here #24

**Comment by fondberg** [comment]
I think there might be a bug in easee as the value doesn't seem to include the latest session. I charged yesterday and haven't unplugged. Session is 6.5KWh and consumption is 2.5KWh. 
I'll monitor what happens when I unplug

**Comment by nsimb** [comment]
mabe this gives no additional use but here is a screenshot from my system today. 
it confuses me a bit since when I compare with the Tibber app (it has consumption used per day from charger) and it claims 1 kwh used today (around 2am). As far as I can see i don't find shorter than 1 month in the easee app.

[
![consuption](https://user-images.githubusercontent.com/34156112/91412153-a6633e80-e849-11ea-85d7-feb37a3d824b.jpg)
](url)

Let me know if I can do anything additional (sadly I just hade the car for 2 weeks so don't have longer time values)

**Comment by fondberg** [comment]
The values this integration provides are straight from the Easee API. The only thing I can think of is that we fetch the last 24 hours of consumption where timber might only fetch from midnight.

**Comment by fondberg** [comment]
I tested it and I get 0 for the last 24H which is not correct. We need to report this to Easee.

**Comment by nsimb** [comment]
Cable lock is now working, closing ticket
