### ISSUE TITLE
Statistics not defined

### ISSUE THREAD

**Issue by MrBamse** [fondberg/easee_hass#257]
### The problem

Hi, it seems as if the Lifetime energy is the only sensor that is defined in such a way that it is supported by Home Assistant long term stats.

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Therefore many of the very useful sensors that I bet you put a lot of work into, and we greatly appreciate it, does not show up as selectable in the Energy dashboard.
https://www.home-assistant.io/more-info/statistics/

Seems like they need to have this configured: "To opt-in for statistics, the sensor must have state_class set to one of the valid state classes: measurement, total or total_increasing."

Any chance I can help out, don't hesitate to let me know.

Cheers :)

### Version of Easee integration having the issue?

Couldn't find this info, but installed the latest update today 20221210

### Version of Home Assistant Core having the issue?

2022.12.1

**Comment by astrandb** [comment]
Thank you for your question.
It is only energy sensors that can be used in the energy dashboard. Other measurements are available as long-term statistics in the statistics card.
We believe the setup is correct, please see https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes

There is also a Session Energy sensor but it does not give any more information to the energy dashboard than the Lifetime sensor.

**Comment by MrBamse** [comment]
Cool, thanks :)
Maybe there could be use cases for the session energy if it's not to much
trouble do add the functionality? :)
Maybe when one starts tracking their energy usage, as for me I got the
charger way before HA and upon adding lifetime energy sensor to the energy
dashboard I got a very "expensive" day of several hundreds of kWh :D

//Ted

**Comment by astrandb** [comment]
Well, I think the Session Energy sensor is less suited as a source for long term consumption. If a reading I missed eg due to temporary HA server outage, the measurement will be gone forever. In addition I think it will confuse the average user to have two different sources for long-time consumption that ideally should show the same result.
As a workaround you can set up a template sensor based on session energy and give it the state_class you find appropriate.

**Comment by olalid** [comment]
Closing this issue since no changes are required.
