### ISSUE TITLE
Make the stop_datetime for setting basic chargeplan optional

### ISSUE THREAD

**Issue by brujoand** [fondberg/easee_hass#259]
### Feature request

I've been playing quite a bit with the basic charge plan because I want the app to show why the car isn't charging and when it will start charging. 

The first thing that made things difficult was that in the easee app you can postpone the charging until a certain time, after that time charging should start. This is how Tibber integrates with easee. But using this HA integration we can't leave out the stop_datetime. Since the schedule has to be only within one day, this means you have create a basic charge plan which starts when the power price is low, and ends at midnight. Then at midnight you'll have to create a new basic charge plan to start charging again. 

So if we could make the stop_datetime optinal the usage of the basic charge plan will be much simpler. 

(to be honest it took me a while to figure out that the charge plan start and stop timespan was when charging was enabled, not disabled) 

### What version of the integration are you using?

v0.9.47

**Comment by astrandb** [comment]
Thank you for reporting.
The UI and the yaml mode allow `stop_datetime` to be empty but it is required in the `pyeasee` library that formats the API call. Therefore the end result is wrong. We put the issue on the todo-list.
