### ISSUE TITLE
Cable locked reporting off when locked

### ISSUE THREAD

**Issue by oveand** [fondberg/easee_hass#262]
### The problem

It seems like cable_locked is reporting off when cable is locked:

`"<template TemplateState(<state binary_sensor.***_cable_locked=off; name=***, id=***, state_lockCablePermanently=False, state_cableLocked=True, device_class=lock, friendly_name=*** Cable locked @ 2022-12-21T23:21:49.086972+01:00>)>"`

While charging, when testing `{{ states('binary_sensor.***_cable_locked') }}` the output is off too.

Is this intentional? It seems a bit contractionary?
It might origin from https://github.com/fondberg/easee_hass/blob/master/custom_components/easee/const.py#L86 ?

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

2022.12.8

**Comment by olalid** [comment]
Well... it is a lock sensor and a lock sensor is off when it is locked and on when it is unlocked. So if you look at it in the UI you should see locked when the cable is locked.
At least that is how it looks for me.

**Comment by astrandb** [comment]
Yes, we are following the docs from Home Assistant. https://developers.home-assistant.io/docs/core/entity/binary-sensor#available-device-classes

**Comment by oveand** [comment]
Sorry, my bad. You are totally right, I got it the wrong way around. I'm closing this and thanking you for your quick feedback.
