### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by felixlangkjaer** [fondberg/easee_hass#264]
### The problem

When I add the Easee integration and enter user name & password I get "Unknown error occurred"?
I have tried to delete the integration, restart, reinstalled the integration, restarted, but same error.

### Version of Easee integration having the issue?

v0.9.48

### Version of Home Assistant Core having the issue?

2023.1.2

**Comment by smultronpop** [comment]
Got same, for me issue was that I had to confirm my account at easee, 
Had received a mail with link

**Comment by felixlangkjaer** [comment]
I have no problem login into to https://easee.cloud/ so that shouldn't be the issue

**Comment by olalid** [comment]
"Unkown error" seems to me like the code probably made some exception, can you please look in the log file if there is anything there related to easee integration?

**Comment by felixlangkjaer** [comment]
Only error related to Eesee is "2023-01-13 10:35:28.086 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant"

**Comment by olalid** [comment]
If you add this to your configuration.yaml, do you see any additional log messages?

´´´
logger:
  default: info
  logs:
    pyeasee.easee: debug
    custom_components.easee: debug
´´´

**Comment by olalid** [comment]
@felixlangkjaer Are you 100% sure that it is not an account confirmation problem as smultronpop mentions?
I have a vague memory that I have seen this before where someone could not get this integration to work and it was related to confirming the account.
I think it was still possible to use the app and log in to the cloud even without that approval, it was just using the API that failed.
Are you sure you have med the required response to the confirmation mail?

**Comment by felixlangkjaer** [comment]
@olalid that helped! I set a new password on easee.cloud and that did it...thanks for the help!
