### ISSUE TITLE
"This entity is no longer being provided by the easee integration. If the entity is no longer in use, delete it in settings." 

### ISSUE THREAD

**Issue by zelloxy** [fondberg/easee_hass#265]
### The problem

I had the integration up and running with Easee integration. But today all entities display this status: "This entity is no longer being provided by the easee integration. If the entity is no longer in use, delete it in settings."

Have they changed their API? Or can this be because their API is down as well?

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

2023.1.6

**Comment by astrandb** [comment]
It is working fine here with the same versions as above. Your problem is probably caused by a temporary glitch in the cloud.

**Comment by zelloxy** [comment]
Still not working for me. Do I have to delete the integration and start over maybe? Just spit balling before taking action :)

**Comment by olalid** [comment]
Can you see anything related to easee in the log file?
What do you see if you click entities on the integration card?

**Comment by zelloxy** [comment]
This is the entity diagnostics:
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "easee": {
      "version": "0.9.48",
      "requirements": [
        "pyeasee==0.7.50"
      ]
    },
    "hacs": {
      "version": "1.29.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "eufy_security": {
      "version": "6.1.1",
      "requirements": [
        "websocket-client==1.1.0",
        "aiortsp==1.3.6"
      ]
    },
    "tibber_custom": {
      "version": "0.5.1",
      "requirements": [
        "matplotlib"
      ]
    }
  },
  "integration_manifest": {
    "domain": "easee",
    "name": "Easee EV charger",
    "version": "0.9.48",
    "documentation": "https://github.com/fondberg/easee_hass",
    "issue_tracker": "https://github.com/fondberg/easee_hass/issues",
    "requirements": [
      "pyeasee==0.7.50"
    ],
    "config_flow": true,
    "codeowners": [
      "@fondberg",
      "@tmjo",
      "@olalid",
      "@astrandb"
    ],
    "iot_class": "cloud_push",
    "integration_type": "hub",
    "loggers": [
      "pyeasee"
    ],
    "is_built_in": false
  },
  "data": {
    "account": {
      "username": "**REDACTED**",
      "password": "**REDACTED**"
    },
    "data": {
      "manufacturer": "Easee",
      "model": "Charging Robot"
    }
  }
}`

I can't find anything when searching the log in regards of Easee unfortunately.

**Comment by olalid** [comment]
Have you enabled logging for the HA component?
If you go to the integration card and press the 3 dots you will find an "activate debug logging" option.
If that does still not show anything in the logs you can try adding this to your configuration.yaml file:

```
logger:
  default: info
  logs:
    pyeasee.easee: debug
    custom_components.easee: debug

```

**Comment by zelloxy** [comment]
Hmm. Nothing showed in the logs at all. But when I pressed configure on the integration it showed that "sites monitored" had been unchecked, meaning no devices of course exists. I wonder what happened for my site to be unchecked. Now it works though, thanks for the incredible assistance.
