### ISSUE TITLE
Sensor data per phase

### ISSUE THREAD

**Issue by bortek** [fondberg/easee_hass#271]
### Question

Hi

I am looking for a way to see Current, Consumption and Voltage per phase. These data is available in the Equilizer. Is there a way to see that? 

### What version of the integration are you using?

latest updated today

**Comment by olalid** [comment]
Current and voltage per phase are attributes to the eq_xx_current and eq_xx_voltage sensors.
Power and energy is not available per phase since that is not something that is provided from the equalizer.
You can of course calculate power per phase by multiplying phase voltage and current.
Example:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/34105674/217663485-98d7b148-4bbb-410d-89c4-7c6dfc43a475.png">

**Comment by olalid** [comment]
Current and voltage per phase are attributes to the eq_xx_current and eq_xx_voltage sensors.
Power and energy is not available per phase since that is not something that is provided from the equalizer.
You can of course calculate power per phase by multiplying phase voltage and current.
Example:
<img width="563" alt="Screenshot 2023-02-08 at 23 22 08" src="https://user-images.githubusercontent.com/34105674/217665011-e97c3528-ea4e-4b2a-9b1c-1aa851c8c5d8.png">

**Comment by bortek** [comment]
Hej Niklas

There were bunch of entities that were disable for the device so I had to enable them first, among those were current and voltage on EQ.

Now I am trying to find what you mentioned and I can only see it like this

<img width="428" alt="image" src="https://user-images.githubusercontent.com/9476606/218105419-e62c2c37-c4ee-4302-878a-3a61be8bc214.png">

If I go to history and look for the entity I still have one entity but those per phase seems to be attributes. 

So I wonder if I want to use them in automations or just make a graph with them how do I do it?

**Comment by olalid** [comment]
There are several ways to use attributes.
You can create template sensors or use template triggers directly in automations.

Typically you access an attribute with a template like this:
{{ state_attr('sensor.eq_xx_voltage', 'state_currentL1') }}

You can test your template it if you go to development tools->templates.
You can see the name of all attributes a sensor has if you go to development tools->states and press the name of the sensor you want to look at.

**Comment by bortek** [comment]
Thanks Ola! You learn new things every day :) I can see it via the dev tools.

**Comment by bortek** [comment]
Hi 

Need to re-open this. I have created a template to extract the values från the attributes and it all looks good. 

template:
  - sensor:
    - name: "Template JO-EQ Current L1"
      state: "{{ state_attr('sensor.jo_eq_current', 'state_currentL1') }}"
      unit_of_measurement: "A"

But the decimals of the current are not being shown. Even the original sensor with totals "sensor.jo_eq_current" does not have it. So it show the values like int instead of float.

I even tested it like this {{ state_attr('sensor.jo_eq_current', 'state_currentL1') }} {{float}} but the conversion does not show it and that is due to the original sensor does not have the value in float.

Any idea ?

**Comment by olalid** [comment]
As you can see in the screenshot I posted above, it does show 1 decimal for me (which is how the code is implemented so that is what I expect).
I guess it is possible that the meter you have does not output any decimals...
If you look in the Easee app, does it show decimals?

**Comment by bortek** [comment]
yes your decimans are shown  just like mine but are 0 just like in mike case. I wonder if you have ever observed it showing anything other than 0? 
Looking at the history per phase and total does not show decimals either. When mouse overing it shows e.g. 7A or 8A or 3A etc.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/9476606/220694395-c223431c-2ab2-4172-8a07-edbd56d187a2.png">


this is from the easee.cloud, no decimals used either

<img width="892" alt="image" src="https://user-images.githubusercontent.com/9476606/220695254-8e54b162-13ef-4408-a595-44adb8682648.png">


I looked in the app and there is the same thing , it shows 8.0A 8.0A 4.0A.

this is kinda bad. Now I am unsure if this is EQ or actually my meter not outputting decimals. 

I was hoping EQ would have been a good substitute to my own built Wemos ESP32 based dongle, but maybe not.

**Comment by olalid** [comment]
My decimals are not 0. You must be looking at the wrong picture...?

**Comment by bortek** [comment]
sorry I was looking at (my :) wrong picture.

So yours are showing decimals correclty and with kommatecken ";".

Interesting. Does the integration care about regional settings like if I have US English Assistant (or on my PC) and therefore delimiter character is not properly used? Just speculating what could be wrong.

On the other hand if the decimals are now shown even in the app and on the easee.cloud then there must be something wrong up there.

**Comment by olalid** [comment]
The regional settings is transparent for the integration, i.e. there is no specific support for converting between , . etc.
That is all handled by HA. So I do not think that has anything to do with it.

To me it feels like the most likely reason would be that the electric company meter at your place just does not output decimals.
Do you know the maker and model number of the meter?

**Comment by bortek** [comment]
Yes it is Sagemcom T211 that Ellevio installed for a month ago.

There a link with pdf at the bottom of this page, it's called Mätare1.
https://www.ellevio.se/privat/om-din-el/elen-i-hemmet/forsta-din-elmatare/

**Comment by olalid** [comment]
Well, hard to tell...
Without actually checking what your meter outputs by using some other means to read the serial data on the port I really can not tell for sure.
If you look at this page though it seems like there should be decimals on the output:
https://www.domoticz.com/forum/viewtopic.php?t=35670
Maybe it is worthwhile to ask Easee support about it, since you are seeing the same thing in the Easee app...
They might be able to see the raw data from the meter in their systems.

**Comment by bortek** [comment]
Will test with my wemos esp32 coming weeks and see what I get out of it. Let's keep this open until then.

**Comment by bortek** [comment]
Hej

Sitting and filling on the settings and trying to figure this out. Will also connect my esp32 reder tomorrow. 

But today I was trying to get the data from the API to see what it actually is showing as a current.

I am using this API toolkit

https://developer.easee.cloud/reference/post_api-access-token

I looked through all the sections but cannot find where I get make an API call to get the actual Current drawn, the one that the HASS Integration  is using to get the data from for the Current. Can you point me into the right direction?

**Comment by bortek** [comment]
Just confirmed that my meter is actually outputing the decimals as it should. Here is the screenshot of the ESPhome output.

So what's left now? Before I start hearing to easee, can we conehow reconfirm that the output from the EQ is missing the decimans? How do I get the output from the API to check it out?

<img width="994" alt="image" src="https://user-images.githubusercontent.com/9476606/230757999-b400be9d-d755-46b1-8774-2bb804b60b7c.png">

**Comment by olalid** [comment]
Well, if you want to use what we are using, you need to implement the signalr streaming protocol.
If you want to prove things to Easee, I would make screenshots from their app.

But a simple way to show what data is coming form the cloud would be to use the pyeasee lib with the following command line:
```
python -m pyeasee -u <user name> -p <password> -r
```

**Comment by bortek** [comment]
The command output shows the current with zeroes as decimals. So nothing wrong with the HASS integration as I thought. I will get in touch with Easee support, which will most likely will not lead to any resolution. Another wat to solve it would be using a P1 splitter but I am not sure if it all is worth a hassle. :) Thanks for your time. Closing the issue.
