### ISSUE TITLE
Easee EV Charger: Set charging cost not updating HASS attributes

### ISSUE THREAD

**Issue by flateric80** [fondberg/easee_hass#274]
### The problem

Hi!

When running the Easee EV Charger: Set charging cost it updates Easee Cloud successfully. But it does not trigger an update of the entity attribute values, i.e. [sensor.easee_???_cost_per_kwh] remains unchanged even tough Easee Cloud is updated. 

### Version of Easee integration having the issue?

0.9.48

### Version of Home Assistant Core having the issue?

2023.2.5

**Comment by olalid** [comment]
Yes, we are aware, a fix is coming soon.
