### ISSUE TITLE
Equalizer: More frequent updates of sensors

### ISSUE THREAD

**Issue by MrBamse** [fondberg/easee_hass#275]
### Feature request

Hi, would it be possible to get more frequent updates of the sensors provided by the Easee Equalizer device?
E.g.  sensor.easee_equalizer_import_energy

### What version of the integration are you using?

0.9.48

**Comment by olalid** [comment]
The short answer is no.

To explain a bit: We are displaying all data that we receive as soon as we receive it.
First of all the equalizer is limited by how often the meter outputs data which is typically with 20 seconds interval. Some data is typically limited to 60 second intervals and some even to 60 minute intervals (i.e the energy meter).
On top of that Easee does some filtering such that if new data is a minor change it is not sent out (to limit bandwidth to/from the servers).

**Comment by MrBamse** [comment]
Cool, thanks for the quick update. :)

My Easee app updates the Equalizer values every 10s though.
Would it be possible to get the ability to set the update frequency, maybe with a minimum of 60s?

Another approach, is there a way to get the value directly from the Equalizer?

**Comment by olalid** [comment]
Again. No, please read my response above again. It is not possible.

**Comment by MrBamse** [comment]
But isn't it sent out if it updates in the Easee app?

**Comment by olalid** [comment]
Again, no.
As I said above: We are displaying all data that we receive as soon as we receive it.
What the app is doing is not really relevant, we have NO control over how often or when we receive the data.

Please do not ask the same question again since the answer will be the same next time also, I have better things to write the same answer over and over again.

**Comment by olalid** [comment]
Well, you started being rude by not accepting my answer.
