### ISSUE TITLE
Custom units mandetory?

### ISSUE THREAD

**Issue by nsimb** [fondberg/easee_hass#28]
Don't know when added but I hade some problems so removed and added the integration again.
When in options for choosing sensors the custom units are now mandatory to be able to Submit
Is this intensional?
Once added one I can submit and then again remove the custom units. However, the conversion does not disappear.
so can't get back my kwh

forgot to add version v0.9.13

**Comment by tmjo** [comment]
That sounds strange. I am able to select and deselect this in my integration, also leaving it totally blank (i.e. kWh). Do you get any error messages?

**Comment by nsimb** [comment]
Yes I get "User input malformed"
It's just the first time after adding the integration. However, if I chose for instance "power kW to W" it accepts my choice and no more error message.
Then I can go back and remove the checkbox again and submit without error.

**Comment by tmjo** [comment]
Could you try to set logger level to debug and send a copy of the log? It would make it easier to see where it goes wrong. The user input malformed may be either the Sites or the Custom units I believe, both were added more or less at the same time, and both were modified to fit the different entity change (switch/sensors etc).

**Comment by nsimb** [comment]
Did set it to debug for just this component but not getting any errors at all. Will try to set everything to debug tomorrow and see if I can catch the error from some other parts.
for now, I just leave you with the GUI error message. Hope to have logs for you tomorrow

![image](https://user-images.githubusercontent.com/34156112/91907585-674e4680-ecaa-11ea-853c-829c9a6b400f.png)

**Comment by nsimb** [comment]
I'm sorry I can't find anything in the logs, did turn on debug on for everything, and tried to find anything in it.
If it only me that has this problem (and again only have when first adding the component) lets just close it. More important things to focus on. I solved it via clicking in the kW to W and submit. then go back and uncheck it. Still got it in W instead of kW but not a big problem for me as long as I keep kWh as I now do.

Thanks for the hard work
