### ISSUE TITLE
Error in request from HA

### ISSUE THREAD

**Issue by hmorkemo** [fondberg/easee_hass#29]
This message appears quite often in the HA log file. The car is not plugged into the charger. 

Logger: easee.easee
Source: /usr/local/lib/python3.8/site-packages/easee/easee.py:42
First occurred: 10:56:42 (15 occurrences)
Last logged: 11:01:10

Error in request to Easee API: {'errorCode': 0, 'errorCodeName': 'Uknown', 'type': None, 'title': 'Something went wrong. Try again', 'status': 500, 'detail': '[Empty in production]', 'instance': None}

**Comment by tmjo** [comment]
I've seen it too randomly. Not 100% sure, but I believe this is due to some problems in communication with the Easee server. They've sold a lot, so wouldn't surprise me if they run in to some capacity issues, and we're requesting every 60s per default.

HTTP code 500 seems to confirm my suspicion:
![image](https://user-images.githubusercontent.com/54450177/91989751-2a796280-ed31-11ea-97f3-3388c2e36268.png)

Anyway, perhaps we could make a better fault handling, or even arrange some kind of logic so an error is only reported if the communication fails more than once in a row or anything like that?

**Comment by hmorkemo** [comment]
Yes. Looks like it might be a server capacity problem.
This is a device that we don't have to know the state of every single minute.
Maybe the request frequency should be reduced, and/or to catch 500-returns and report only if there are >1/2/3/4 failures in a row.
That way, there will be fewer errors in the HA log, and nobody will actually notice.

**Comment by tmjo** [comment]
The scan interval depends a bit on how it is used, my intention for instance is to have my own limitation of the charger if power consumption in the house or on a specific circuit goes beyond a value. But anyway, I agree that it is very annoying with such errors in the log, so just leave the issue open and let's see if we can find a good way to handle it. Did you check the details in the log? It says 15 occurrences, but does it seem like they come completely random or is it more or less 15 after eachother timewise?

**Comment by hmorkemo** [comment]
The details say that the errors usually appear in pairs: One for the _days_1 sensor and one for _days_30.
Usually there's a few hours between the occurences.
I guess catching these errors and trying one/two/three more times a few seconds later should help?

**Comment by hmorkemo** [comment]
Sorry, those times were from the read sensor requests. (However, I think they should be fixed too...)
The Error in request to Easee API: status 500 etc. all appeared between 10:56:42 and 11:01:10, in less than 5 minutes.

**Comment by tmjo** [comment]
For the record, I am also seeing the following error messages more or less frequently in addition to 500 Internal Server Error:

503 Service Temporarily Unavailable
504 Gateway Timeout

I believe they are all related to failures on Eeasee side of the API (or overloading it). 

To be investigated.

**Comment by tmjo** [comment]
Adding

429 Too Many Requests

to the list of errors received by API. I've contacted Easee to (hopefully) get some input on how often we can poll info, if is a temporary hickup due to high traffic and if there are other options we could use for communication.

**Comment by fondberg** [comment]
Will be fixed in #47

**Comment by fondberg** [comment]
Can you test with the new release?

**Comment by hmorkemo** [comment]
It's getting better! Here's the easee-related errors from home-assistant.log since it started at 07:44 this morning. HA 0.161.1.
[easee-errors.log](https://github.com/fondberg/easee_hass/files/5353533/easee-errors.log)

**Comment by fondberg** [comment]
Try this which should remove a lot of errors: https://github.com/fondberg/easee_hass/releases/tag/v0.9.19

**Comment by TheAzzi** [comment]
Not my issue, but while testing version 0.9.19 it seems to do fairly well in terms of random error messages.

But you could perhaps consider to handle "503 Service Temporarily Unavailable" better, as it still generates quite some noise in the logs:

2020-10-15 16:38:26 ERROR (MainThread) [pyeasee.easee] Server failure(503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
 https://api.easee.cloud/api/sites/31225/state)
2020-10-15 16:38:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 245, in refresh_sites_state
    sites_state[site.id] = await self.easee.get_site_state(site.id)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 201, in get_site_state
    state = await (await self.get(f"/api/sites/{id}/state")).json()
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 93, in get
    await self.check_status(response)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 106, in check_status
    await raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 47, in raise_for_status
    raise ServerFailureException(data)
pyeasee.exceptions.ServerFailureException: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
2020-10-15 16:39:26 ERROR (MainThread) [pyeasee.easee] Server failure(503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
 https://api.easee.cloud/api/sites/31225/state)
2020-10-15 16:39:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/easee/controller.py", line 245, in refresh_sites_state
    sites_state[site.id] = await self.easee.get_site_state(site.id)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 201, in get_site_state
    state = await (await self.get(f"/api/sites/{id}/state")).json()
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 93, in get
    await self.check_status(response)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 106, in check_status
    await raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/pyeasee/easee.py", line 47, in raise_for_status
    raise ServerFailureException(data)
pyeasee.exceptions.ServerFailureException: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

**Comment by astrandb** [comment]
503 is sent from the Easee cloud servers now and then. It is on the TODO list to handle the error in a better way.
