### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by Birdman86** [fondberg/easee_hass#296]
### The problem

It seems that the translations for this integration is broken since updating to HA 2023.4.
All states are reported as code values, instead of the translations.
Not even the English states are reported correctly.

### Version of Easee integration having the issue?

v0.9.48

### Version of Home Assistant Core having the issue?

2023.4.2

**Comment by astrandb** [comment]
@Birdman86 What is your preferred language?

**Comment by Birdman86** [comment]
Latest version fixed this for me.
