### ISSUE TITLE
Circuit current fails to update after update to version  v0.9.49

### ISSUE THREAD

**Issue by gulli1986** [fondberg/easee_hass#304]
### The problem

I have two chargers connected in series.
After update to  v0.9.49, the second charger (the "slave") is reporting a log fail in HA `Update for sensor.garage_circuit_current fails`.
Everything else is working fine, only the `circuit_current` is failing.

See logs for further information.

The main charger is still reporting fine. The second charger was reporting fine before update to v0.9.49.
Anything new in the code that can explain why this is not working anymore?

### Version of Easee integration having the issue?

v0.9.49

### Version of Home Assistant Core having the issue?

core-2023.4.5

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/easee/entity.py", line 260, in async_update
    self._state = self._state_func(self.data.state)
  File "/config/custom_components/easee/const.py", line 368, in <lambda>
    if state["circuitTotalPhaseConductorCurrentL1"] is not None
  File "/usr/local/lib/python3.10/site-packages/pyeasee/utils.py", line 55, in __getitem__
    if type(self._storage[key]) == str and validate_iso8601(self._storage[key]):
KeyError: 'circuitTotalPhaseConductorCurrentL1'
```
```


### Additional information

_No response_

**Comment by olalid** [comment]
Hi, before v0.9.49, did the circuit_current sensor for the slave charger actually work, or did it just show 0 or some other static value always?
Perhaps we should just remove the circuit_current sensor for slave chargers if it is not useful...

**Comment by gulli1986** [comment]
@olalid you have a point here, it may actually be that the sensor reported 0. I have actually never use this sensor so you might be right.
I think you should also just remove the sensor, the value are given in the circuit_current sensor of the master charger anyway so it is not really useful as I see it.

As it is now it is just giving a lot of error logs in HA.

**Comment by olalid** [comment]
@gulli1986 would you be able to test if the fix in this PR works for you?

https://github.com/fondberg/easee_hass/pull/306/files

**Comment by gulli1986** [comment]
Hello @olalid , will do.
I haven't done that before, should I just replace my const.py and controller.py files with the new ones and restart HA to test?

**Comment by olalid** [comment]
Yes, exactly, just replace them in your custom_components/easee folder and restart.

**Comment by gulli1986** [comment]
Hello @olalid. I finally got time to try your PR.
That worked fine, looks like the circuit current sensor is now gone, hence solving the issue.

Thanks again for your help!
