### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Mats1717** [fondberg/easee_hass#307]
### Question

I want the entities to be in englich but I cant chose that, they be in swedish all the time.
What can i do to change that?

### What version of the integration are you using?

V0.9.49

**Comment by astrandb** [comment]
Translation of entity names is controlled by the global language setting (Settings->General->Language).

**Comment by Mats1717** [comment]
Thank you, easy when you know where to look :)

**Comment by astrandb** [comment]
I also think it is confusing that there are two different language settings in HA, one global that affects e.g. entity names and one personal (in personal profile) that affects states and attributes. I have not seen any explanation why the core team chose that design.
