### ISSUE TITLE
Multi Accounts

### ISSUE THREAD

**Issue by CBAMav** [fondberg/easee_hass#310]
### Feature request

Hi,
I would like to monitor my two Easee wallboxes and those of my parents. however, when I want to add a second instance I get the message that only one instance is supported. is it possible to extend this to several or how could I get around the problem?

![image](https://user-images.githubusercontent.com/29519309/234519836-61860a97-edde-4ec1-a180-eb0bfc06b8ef.png)

### What version of the integration are you using?

easee-

### Anything in the logs that might be useful for us?

```txt
all Systems are Easee-Home
```

**Comment by astrandb** [comment]
I took a quick tour around the code-base and there are a few blockers when it comes to automations and scripts.
A possible workaround is to use the same Easee account for yourself and for your parents. Perhaps you can test if your parents can make you a user of their charger or vice versa. You could also ask Easee if they have any ideas how to set up the accounts to achieve your goal. You don't have to refer to Home Assistant in your question. Same problem in the Easee app.

**Comment by olalid** [comment]
Could this not be solved by asking your parents to invite you as a user to their site?
In the Easee app you can do this by pulling down to reveal the site information and press "Members" and then "Invite user".
If you use the same account that you use for your own charger(s) I would assume you can then enable that site in the Easee integration settings. I.e. multiple sites are already supported if they visible for a single account.
A restart of the integration would be required for it to show up in the integration settings.

**Comment by CBAMav** [comment]
Thank you so much for your tips. I will visit my parents this weekend and try to get invited to their site.

**Comment by CBAMav** [comment]
My parents had invited me and now i can monitor all 3 chargers. Thx for helb
