### ISSUE TITLE
Can not Select location at config

### ISSUE THREAD

**Issue by RafSchandevyl** [fondberg/easee_hass#325]
### The problem

Hi, 

I'm trying to configure this integration, but after i give username & password, it asks for a location. there is no input field, and also no selection list. 

So i can't configure the integration.

Regards
Raf

### Version of Easee integration having the issue?

0.9.52

### Version of Home Assistant Core having the issue?

2023.5.2

**Comment by olalid** [comment]
Hmm, I do not think this location information is part of the integration in any way.
It is rather something that HA itself uses to categorize units/entities to where they are physically located.
If you look under settings->Areas/Zones, do you have anything configured there?
That is what you should see in that dropdown I am pretty sure.

I would also try reloading the HA page in the browser and try again, seems to me like som kind of HA user interface issue, and that sometimes occur if something outdated is cached in the browser.

**Comment by olalid** [comment]
Or do you mean site when you say location?
Might be a bit confused by translations here.
Can you make a screenshot?

**Comment by RafSchandevyl** [comment]
![Schermafbeelding 2023-05-11 110318](https://github.com/fondberg/easee_hass/assets/78409275/97ae2022-1f6f-4594-84d1-795ef9d6a7e5)

**Comment by olalid** [comment]
Ah, ok, original english word is sites so that confused me, sorry.

If you log in to the easee cloud webpage with the same user that you are using for the integration and go to https://easee.cloud/sites
Do you see your site(s) listed there?

**Comment by astrandb** [comment]
The most likely problem is that no site is available for the used account. 

The dialog on the screen shot above should only be displayed if there are > 1 site available, now it pops up also for zero sites. 
I think the `config_flow` should be adjusted to produce a meaningful error message in this case.

@RafSchandevyl - there must be a misconfiguration in your account with Easee.

**Comment by RafSchandevyl** [comment]
Hi,

When i log in on the cloud is have 2 sites listed.

![Schermafbeelding 2023-05-13 075645](https://github.com/fondberg/easee_hass/assets/78409275/eede7c45-4b42-4d8a-b658-aa241531b57d)

**Comment by astrandb** [comment]
We have seen a few examples that there are inconsistencies between the cloud site and the Easee app. 

Please make sure your sites and chargers are available as expected in the app. Open the Easee app on your phone, make sure you are logged in as the same user you are using in the HA integration.

Click the to the hamburger menu / Products / Clicking the add button then the "Locate site" button at the bottom of the page. That should list out the sites you have access to and below that level the products. You should then be able to add any charger and/or equalizer to the app.

You can also enable full debug logging for the integration in HA, with a little luck it will show what happens in the early phase of setup even if the setup never completes.
Enter following in configuration.yaml and restart HA and then reinstall the integration.
```yaml
logger:
  default: info
  logs:
    custom_components.easee: debug
    pyeasee: debug
```
