### ISSUE TITLE
set_circuit_dynamic_limit cannot find circuit_id

### ISSUE THREAD

**Issue by ujhede** [fondberg/easee_hass#328]
### The problem

When calling the set_circuit_dynamic_limit function with the circuit_id as a parameter an error that the circuit id cannot be found. See call below.

When calling the same service using the device_id it works.  I have confirmed that the circuit_id is corrent I can even see in the debug logs that the easee api is called with this circuit_id.

It seems that somehow HA has gotten the idea that device_id is the only valid id parameter.  In the development tools service tab device_id is the only parameter that will turn the "Call Service" button blue.  

service: easee.set_circuit_dynamic_limit
data:
  circuit_id: 34XXXX
  currentP1: 16
  currentP2: 16
  currentP3: 16

### Version of Easee integration having the issue?

0.9.52

### Version of Home Assistant Core having the issue?

2023.5.3

### Anything in the logs that might be useful for us?

```txt
2023-05-20 11:58:58.600 DEBUG (MainThread) [custom_components.easee.services] Execute_service: set_circuit_dynamic_limit {'circuit_id': '34XXXX', 'currentP1': 16, 'time_to_live': 0}
2023-05-20 11:58:58.600 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Could not find circuit 34XXXX
```

**Comment by olalid** [comment]
There is a limitation in how HA works, we are not able to support the circuit_id (or charger_id) in the UI when we have the device_id as the default ID.

But yes, there seems to be something wrong with the circuit_id: support in the latest version(s), I can repeat the problem.

**Comment by olalid** [comment]
The fix seems to be simple, this must have broken for a while.
Thanks for letting us know.

**Comment by olalid** [comment]
See https://github.com/fondberg/easee_hass/pull/329
