### ISSUE TITLE
Easee component not starting

### ISSUE THREAD

**Issue by patrik996** [fondberg/easee_hass#33]
HASS version 0.114.4
Easee component version: 0.9.13
Installed using HACS.

I haven´t figured out how to get this component running. Home assistant log says that the component is loaded:
2020-09-14 12:46:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for easee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

But it does not show up it Intregrations. And I cant find any entity or any service related to easee.

I have set the log to debug( custom_components.easee: debug ), but it logs absolutely nothing.

I have tried uninstalling and reinstalling the component using hacs. ( made sure no cache was left after uninstall)

Do you have any idea?

**Comment by patrik996** [comment]
And yeah i have easee enabled in configuration.yaml :)

easee:

**Comment by tmjo** [comment]
Hi,

When you say it doesn't show up in integrations, do you mean in your list of active integrations or in the list where you add integrations? It has to be added (+ button on integrations page) and there you add your username/password to login to the Easee account. But if it doesn't appear in the add list there, my best guess is to do a forced update of the webpage (CTRL+F5 in Chrome) to make sure the UI is updated.

**Comment by patrik996** [comment]
Hehe I feel pretty stupid now. I missed that i needed to add it with the + button. Thanks!
