### ISSUE TITLE
Arbitrary api calls

### ISSUE THREAD

**Issue by whi-tw** [fondberg/easee_hass#338]
### Feature request

I’d like to set the weekly schedule - that’s not possible, so I wondered if it was possible to send arbitrary calls to Easee’s api (via pyeasee)?

### What version of the integration are you using?

latest

**Comment by olalid** [comment]
No, there is no support for setting weekly schedules, but it could of course be added...

You could also create a python script that uses pyeasee to accomplish it, outside of HA, since pyeasee has support for it. I have never tested this function in pyeasee, but hopefully it works...

**Comment by whi-tw** [comment]
I’ll have a play at implementing it - I’m using [pyscript](https://github.com/custom-components/pyscript) for processing some data from my energy company to schedule charging for arbitrary 0 / negative cost blocks during the day, and want to throw in a schedule to not have to deal with starting and stopping the charger via the api.

Using pyeasee directly would be an idea, but I like the idea of hass being the orchestrator / managing the API connection.

**Comment by olalid** [comment]
Yes, we will probably add that functionality some time in the future, it does make sense to have.
Just do not expect it to happen next week :)

**Comment by olalid** [comment]
See https://github.com/fondberg/easee_hass/pull/347

**Comment by olalid** [comment]
There is now a new service for setting weekly schedules.
You need to call it once for each weekday to set for all days in a week.
To start over you need to delete the whole schedule (a separate action command service) and start over.
