### ISSUE TITLE
Current and Voltage missing in EQ

### ISSUE THREAD

**Issue by bortek** [fondberg/easee_hass#340]
### Question

Just reinstalled the integration one more time using the latest code from git (git cloned).'

The problem I have is that EQ is no longer showing Current and Voltage. 

I am pretty sure it has been present in the entities since I made a template to extract current per phase.

Now it looks like this.

Has it been removed?

<img width="878" alt="image" src="https://github.com/fondberg/easee_hass/assets/9476606/0bb56cb3-3160-4502-9f98-8d23369cc49f">

<img width="402" alt="image" src="https://github.com/fondberg/easee_hass/assets/9476606/dbcad90a-62b3-4749-b187-d5376a2b3e43">

### What version of the integration are you using?

latest

**Comment by bortek** [comment]
Here are the versions

config $ grep "Setting up Easee component" home-assistant.log
2023-08-03 16:54:41.154 DEBUG (MainThread) [custom_components.easee] Setting up Easee component version 0.9.54

config $ grep "Easee python library" home-assistant.log
2023-08-03 16:54:40.503 INFO (MainThread) [pyeasee.easee] Easee python library version: 0.7.53
2023-08-03 16:54:41.154 INFO (MainThread) [pyeasee.easee] Easee python library version: 0.7.53

**Comment by bortek** [comment]
You are damm right :) . When I clicked on them they were showing "unavailable". Normally when they are being not enabled they show "disabled". But when I pressed the "kugghjul" button there was an option to enable/disable. I enabled it and after 1 minute the data started to show up. 

But then a question is why they are not enabled by default? Is this something you can toggle in the integration so they will be on by default?

**Comment by olalid** [comment]
Some of the more "exotic" sensors are disabled by default and needs to be manually turned on.
This is to keep the number of default sensors at a somewhat reasonable level.

**Comment by bortek** [comment]
Can we have this documented ? I can edit the README and make a PR.
