### ISSUE TITLE
Sensors show not available

### ISSUE THREAD

**Issue by Djac-HA** [fondberg/easee_hass#343]
### The problem

Since a while all my easee sensors shows up as unavailable, removing and adding back the device doesn't help?

### Version of Easee integration having the issue?

09.48

### Version of Home Assistant Core having the issue?

23.8.2

**Comment by olalid** [comment]
Please try to upgrade to the most recent release of the Easee integration and get back to us if the problem remains.

**Comment by Djac-HA** [comment]
Thanks for this, and I am sorry I didn't notice this myself, works fine after upgrade.
