### ISSUE TITLE
Charge Lite

### ISSUE THREAD

**Issue by Mats1717** [fondberg/easee_hass#346]
### The problem

Installed the new Charge Lite today together with my old Easee Home. Had to install both as master because the Light did not work as slave. Can not recive any data from from the Lite. Is it a change in the API for this and will this be solved in future relises.
In the cloud all chargers are there.

Regards Mats

### Version of Easee integration having the issue?

Latest

### Version of Home Assistant Core having the issue?

Latest

**Comment by olalid** [comment]
Have you added the new charger to the Easee phone app? It will not be visible in the integration unless you do that.

**Comment by Mats1717** [comment]
Yes it is added to the app and working there.

**Comment by Mats1717** [comment]
Not sure what happend, had in in the app but when i checked now it was gone.
Added the second charger now and it is working and finding 2 chargers.
Thanks for support
