### ISSUE TITLE
Half of my sensors are disabled by integration. 

### ISSUE THREAD

**Issue by FSHelgeland** [fondberg/easee_hass#349]
### Question

Half of my sensors ar disabled by the integration. Some of them are logical and others are not. The sensors I miss the most is Voltage (Spenning) and current (Strøm). I guess they are missing because Tibber is controlling the charger but I am not sure. 

### What version of the integration are you using?

idk

**Comment by olalid** [comment]
Some of the sensors are intentionally disabled, but you should be able to enable them. Do you mean that you cannot enable them or that you do not know how to enable them?

**Comment by FSHelgeland** [comment]
aha, never taught of that. They are enabled now. Thank you.
