### ISSUE TITLE
Upcoming easee api domain change

### ISSUE THREAD

**Issue by ThomUK** [fondberg/easee_hass#354]
### Question

According to this page, on 3rd October 2023 the easee api url will change from api.easee.cloud to api.easee.com
https://developer.easee.cloud/docs/integrations-30

Having searched the code, I can only see easee.cloud urls, so it's possible this integration will stop working on 2023-10-03.
The new domain is already active and available for use.

### What version of the integration are you using?

0.9.54

**Comment by olalid** [comment]
Don't worry, it is already taken care of.
(It is part of the lib, see https://github.com/fondberg/pyeasee)

**Comment by ThomUK** [comment]
Great, apologies I didn't spot that. Thank you I'll close this issue if I can.
