### ISSUE TITLE
Entity equivalent to RFID Authorization

### ISSUE THREAD

**Issue by TheFreaker86** [fondberg/easee_hass#361]
### Question

Hallo!
I am searching for an entity I can trigger which equals to using the RFID keyfob authorizing the start of charging the EV with the Easee Home. My goal is to create an action on my Apple Watch to authorize the charge. Is there any entity to do this? Charger activate is switching the charger off completely, isn't it?

Thanks for your help!

### What version of the integration are you using?

0.9.55

**Comment by StevoNL** [comment]
Create an automation to call the start action. The GUI is quite self explanatory. The YAML equivalent will be:
`action:
  - service: easee.action_command
    data:
      device_id: <your_device_id>
      action_command: start`

**Comment by TheFreaker86** [comment]
Thank you very much! That was much easier than anticipated!
