### ISSUE TITLE
How do I change the password?

### ISSUE THREAD

**Issue by Svardsten53** [fondberg/easee_hass#44]
I have changed the password to Easee cloud but can't find any way to change it in the integration. Adding it to easee: section in configuration.yaml resulted in configuration error: Maybe it's not possible or I didn't do it in a proper way. If possible some documentation would be very nice. I can't find the source directory listed below.

Clicking 'Alternativ' in the integration just results in an endless message for the integration to be installed.

Logger: easee.easee
Source: /usr/local/lib/python3.8/site-packages/easee/easee.py:31
First occurred: 21:58:39 (1 occurrences)
Last logged: 21:58:39
Bad request service (400: {'errorCode': 100, 'errorCodeName': 'InvalidUserPassword', 'type': None, 'title': 'Username or password is invalid', 'status': 400, 'detail': '[Empty in production]', 'instance': None} https://api.easee.cloud/api/accounts/token)

**Comment by olalid** [comment]
Yes, you are probably correct in that it is not possible to change the password as the component is implemented.
Have you tired removing the integration and re-adding it again?

**Comment by Svardsten53** [comment]
I have now reinstalled the integration and problem is solved. A little bit strange that I needed to use another format of my phone number (had to add +46) as user when logging in to Easee cloud compared to the one used when logging in via home page.
