### ISSUE TITLE
Configured area for the device disappears

### ISSUE THREAD

**Issue by TheAzzi** [fondberg/easee_hass#49]
Hi,
Running latest HA (0.115.6) and latest Easee charger component (0.9.16).
Tested in two different HA instances.

How to replicate:
- Configure an area for the Easee device
- Change something in Options (i.e. add a monitored sensor)
- Observe the area for the Easee device is now listed as "No area"

**Comment by fondberg** [comment]
This is unfortunately by design. If you know a way to do it differently then you are welcome to share. We didn't find another way
