### ISSUE TITLE
Minor annoyance in friendly name of entities

### ISSUE THREAD

**Issue by TheAzzi** [fondberg/easee_hass#66]
Testing version 0.9.19 and it makes sense to use the charger name in the friendly name as you now do.
However there is a minor annoyance where you seem to convert the charger name to lowercase.
In example my charger is named "Easee Home 01".
The device in HA is named correctly "Easee Home 01".
But the entities in HA is named "Easee home 01*", in example "Easee home 01 status". (Note the lowercase "h")

**Comment by olalid** [comment]
@TheAzzi please take a look at the latest release.

**Comment by TheAzzi** [comment]
The friendly names looks good now. Thanks! :)
Another minor annoyance I noticed while upgrading to this version;
There is a typo in the name in HACS, the component is now called "Easee CV Charger" ("CV" instead of "EV").

**Comment by olalid** [comment]
@TheAzzi should be fixed now, please check 0.9.21.

**Comment by TheAzzi** [comment]
Looks good! Thanks.
