### ISSUE TITLE
Minor name change suggestion

### ISSUE THREAD

**Issue by rasssta** [fondberg/easee_hass#92]
`sensor.easee_[...]_in_current` should be named `sensor.easee_[...]_input_current` to match with `sensor.easee_[...]_output_current`.

**Comment by olalid** [comment]
Yes, agree that it looks strange.
It is however how Easee has named the parameters in the API.
inCurrentTx vs outputCurrent.
I think outputCurrent actually means "currently signalled maximum allowed current to the car" and it is not a measured current, it is what the charger has concluded is the current the car can use at this point in time without overstepping any of the current limits.
While inCurrent is the current it measures actually consumed by the car.
So not sure what is best. Keep something that is close to the naming Easee uses, change to your suggestion or coming up with something that is more self-explanatory?
I would think "Charging current" and "Signalled max current" perhaps would be more understandable for the user.

**Comment by rasssta** [comment]
Oh, I see. Interesting naming solution from Easee.

I agree that the names in use right now are somewhat misleading, at least not very clear. You seem to be on to something with your suggestions. As you have all the data from Easees API, feel free to present a summary of all the names / naming schema and I'll happily discuss it with you here :-)

I've currently (re)named mine like this (but I'm not happy with some of them, like "Is enabled") ;-)

![image](https://user-images.githubusercontent.com/4455235/106906853-e2a2a100-66fd-11eb-93a7-69fbf943c757.png)

**Comment by olalid** [comment]
I guess output is in the sense that is the output from the current limiting algorithm.
I will look in to it later this evening.

**Comment by olalid** [comment]
Sorry for the delay, the shit hit the fan when some of the libs we are using made incompatible updates...
Anyway, I have created a PR with some changes to sensor names, consider it a suggestion (I linked it to this issue).
If you have an opinion please let us know.

**Comment by rasssta** [comment]
Looks good! :)
