### ISSUE TITLE
Basic schedule binary sensor

### ISSUE THREAD

**Issue by prilly-dev** [fondberg/easee_hass#95]
Binary sensor basic schedule is not reporting the correct time/date for the current schedule.

![Skjermbilde](https://user-images.githubusercontent.com/66376450/106856612-08f51c00-66bf-11eb-9e3b-aaf4d2b864df.JPG)

**Comment by tmjo** [comment]
Hi! Is this the result when you have a schedule activated in easee? Has it been activated for a while, or did you just activate it? Is it repeating?

Mine is showing values fine, I have a repeating schedule from 23:00 to 09:00 every day. Could be helpful to activate debugging log and check for details, perhaps something went wrong.

**Comment by prilly-dev** [comment]
Schedule have been tried with repeat on and off, no difference.

What i have discoverd is that the entity was last updated days ago. It might be that the entity is not updated with easee cloud on a regular basis. Last updated in dev tools in ha shows the entity was last updated 3. Feb at 15.44

**Comment by prilly-dev** [comment]
I tried to reload the integration "last inn på nytt" then the entity is showing the correct values.

**Comment by tmjo** [comment]
Good. I had some error messages related to this sensor a while back, but it seemed to be only on initial startup and I didn't have time to verify it yet. It may or may not be related, but I recommend setting log to debug-level and look for anything about that specific sensor. It makes it easier to know what is going on.

**Comment by prilly-dev** [comment]
It seems to work just fine now, changing schedule in the easee app is properly updated in ha. That reload integration might have fixed it. I am closing this issue now.
